[profile.default]
libs = ["node_modules", "lib", ".venv/lib/python3.13/site-packages"]
skip = ["**/site-packages/snekmate/**", "src/modules/**"]
show_metrics = true
via_ir = true
optimizer = true
optimizer_runs = 200
vyper_version = "0.4.3"

# Add remappings
remappings = [
    "solmate/=lib/solmate/src/",
    "solady/=lib/solady/src/",
    "@uniswap/v4-core/=lib/v4-periphery/lib/v4-core/",
    "@uniswap/v4-periphery/=lib/v4-periphery/"
]

fs_permissions = [
    { access = "read", path = "./addresses" }
]
